### ISSUE TITLE
ISSI 62C256AL-45ULI 28-PIN SOP

### ISSUE THREAD

**Issue by nbdy32** [FraEgg/commodore-1541-floppydrive-8x-multi-floppy-speeder#1]
The chip is larger than the pads on the PCB ...

Werry hard to solder them on the board ...

**Comment by FraEgg** [comment]
Thank you for your message. The SMD RAM should be soldered in carefully. I have changed the footprint in the upcoming version 1.7 to make soldering a bit easier. 

You can test the RAM well with The Final Cartridge 3 on the C64. In the freezer menu, my monitor has an OD command that allows you to switch to the 1541 and test the RAM of the floppy directly.

If you have any questions, I will be happy to help you.
